version: "3.9"
services:
    web:
        build: .
        ports:
            - "8080:80"
        depends_on:
          - rabbitMQ
        networks:
          - rabbitmq_go_net          
    rabbitMQ:
      image: rabbitmq:3.9-management-alpine
      container_name: 'rabbitMQ'
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge